#!/usr/bin/env python3
"""
Convert PNG icons to LVGL CF_TRUE_COLOR_ALPHA C arrays.

Scans icons/out/ (and icons/ for loose PNGs like logo.png) for files
whose names match an asset referenced by an existing C file under
src/display/ui/default/lvgl/images/, then overwrites that C file.

Usage:
    python scripts/convert_icons.py          # convert all matched icons
    python scripts/convert_icons.py --list   # show available icon names
    python scripts/convert_icons.py --check  # dry-run, print matches only

Requirements:
    pip install Pillow
"""

import argparse
import re
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow is required: pip install Pillow")
    sys.exit(1)

IMAGES_DIR = Path("src/display/ui/default/lvgl/images")
ICON_DIRS  = [Path("icons/out"), Path("icons")]


def build_asset_map() -> dict:
    """Return {asset_basename: (c_path, var_name)} from existing C files."""
    asset_map = {}
    for c_file in sorted(IMAGES_DIR.glob("*.c")):
        text = c_file.read_text(encoding="utf-8")
        m = re.search(r"// IMAGE DATA: assets/(.+)", text)
        if not m:
            continue
        asset_name = m.group(1).strip()
        vm = re.search(r"const lv_img_dsc_t (\w+) =", text)
        if not vm:
            continue
        asset_map[asset_name] = (c_file, vm.group(1))
    return asset_map


def find_png(asset_name: str) -> Path | None:
    """Search icon dirs for a PNG matching asset_name."""
    for d in ICON_DIRS:
        p = d / asset_name
        if p.exists():
            return p
    return None


def rgb_to_rgb565(r: int, g: int, b: int) -> tuple[int, int]:
    """Return (low_byte, high_byte) of RGB565 little-endian encoding."""
    low  = ((g >> 2 & 0x07) << 5) | (b >> 3)
    high = (r >> 3) << 3 | (g >> 5)
    return low, high


def generate_c(png_path: Path, var_name: str, asset_name: str) -> str:
    img = Image.open(png_path).convert("RGBA")
    w, h = img.size
    pixels = list(img.getdata())

    hex_bytes = []
    for r, g, b, a in pixels:
        lo, hi = rgb_to_rgb565(r, g, b)
        hex_bytes += [f"0x{lo:02X}", f"0x{hi:02X}", f"0x{a:02X}"]

    # 21 values per line (7 pixels × 3 bytes) matches SquareLine output style
    lines = []
    for i in range(0, len(hex_bytes), 21):
        lines.append("    " + ", ".join(hex_bytes[i:i + 21]) + ",")
    if lines:
        lines[-1] = lines[-1].rstrip(",")

    data_name = f"{var_name}_data"
    padding   = " " * (len(f"const lv_img_dsc_t {var_name} = ") - 1)

    return (
        f"// This file was generated by scripts/convert_icons.py\n"
        f"// LVGL version: 8.3.11\n"
        f"// Project name: GaggiMate\n"
        f"\n"
        f'#include "../ui.h"\n'
        f"\n"
        f"#ifndef LV_ATTRIBUTE_MEM_ALIGN\n"
        f"#define LV_ATTRIBUTE_MEM_ALIGN\n"
        f"#endif\n"
        f"\n"
        f"// IMAGE DATA: assets/{asset_name}\n"
        f"const LV_ATTRIBUTE_MEM_ALIGN uint8_t {data_name}[] = {{\n"
        f"{chr(10).join(lines)}\n"
        f"}};\n"
        f"\n"
        f"const lv_img_dsc_t {var_name} = {{.header.always_zero = 0,\n"
        f"{padding} .header.w = {w},\n"
        f"{padding} .header.h = {h},\n"
        f"{padding} .data_size = sizeof({data_name}),\n"
        f"{padding} .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n"
        f"{padding} .data = {data_name}}};\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--list",  action="store_true", help="List all replaceable icon asset names")
    parser.add_argument("--check", action="store_true", help="Dry run — show what would be converted")
    args = parser.parse_args()

    asset_map = build_asset_map()

    if args.list:
        print(f"{'Asset name':<45} {'C file':<35} Found in icons/")
        print("-" * 100)
        for asset_name, (c_path, var_name) in sorted(asset_map.items()):
            found = find_png(asset_name)
            mark  = str(found) if found else "(not found)"
            print(f"{asset_name:<45} {c_path.name:<35} {mark}")
        return

    converted = 0
    skipped   = 0
    for asset_name, (c_path, var_name) in sorted(asset_map.items()):
        png = find_png(asset_name)
        if not png:
            skipped += 1
            continue
        img  = Image.open(png)
        size = f"{img.width}×{img.height}"
        if args.check:
            print(f"  WOULD  {png}  →  {c_path.name}  ({size}, var={var_name})")
        else:
            c_path.write_text(generate_c(png, var_name, asset_name), encoding="utf-8")
            print(f"  OK     {png.name:<40} → {c_path.name}  ({size})")
        converted += 1

    print(f"\n{converted} icon(s) {'would be ' if args.check else ''}converted, {skipped} skipped (no matching PNG).")
    if skipped and not args.list:
        print("Run with --list to see all asset names and where to place PNGs.")


if __name__ == "__main__":
    main()
